my:
  greeting: Hello
  list.values: One,Two,Three
  example.dbValues: "{connection: 'https://____', userName: 'user', password: 'admin'}"
db:
  login: login
  password: password
  port: 1521
  host: 127.0.0.1

management.endpoints.web.exposure.include: "*"

spring.profiles.active: test