my:
  greeting: Hello
  list.values: One,Two,Three
  example.dbValues: "{connection: 'https://____', userName: 'user', password: 'admin'}"
db:
  login: login-test
  password: password-test
  port: 2400
  host: 129.0.0.1

management.endpoints.web.exposure.include: "*"